# Generated by Django 4.0.3 on 2022-03-22 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.SlugField(
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(default="", max_length=255)),
                ("description", models.TextField()),
                ("explore_layout", models.JSONField()),
                ("detail_layout", models.JSONField()),
            ],
            options={
                "ordering": ["title"],
            },
        ),
    ]
