version: '3'

services:
  api:
    build: backend
    depends_on:
      - postgis
    environment:
      PGHOST: postgis
      PGUSER: djangouser
      PGPASSWORD: djangopassword
      PGDATABASE: django
    ports:
      - '8000:8000'
    restart: always

  dashboard:
    build: frontend
    volumes:
      - './frontend:/usr/src/app'
    ports:
      - '3000:3000'
    command: 'sh -c "npm install && npm start"'

  postgis:
    build: data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dashboard
      DJANGO_DB: django
      DJANGO_USER: djangouser
      DJANGO_PASSWORD: djangopassword
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - postgis:/var/lib/postgresql/data
      - ./data/datasets:/datasets:ro

  postprocessor:
    build: data/postprocessor
    depends_on:
      - postgis
    environment:
      PGHOST: postgis
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: dashboard
    volumes:
      - ./data/datasets:/datasets:ro
      - ./data/postprocessor/scripts:/scripts:ro

  psql:
    build: data
    depends_on:
      - postgis
    entrypoint: ["psql"]
    environment:
      PGHOST: postgis
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: dashboard
    profiles:
      - psql
    volumes:
      - ./data:/data:ro

volumes:
  postgis: {}
