[tool.black]
line-length = 80
target-version = ['py310']
include = '\.pyi?$'

[tool.pylint.messages_control]
disable = "C0330, C0326"

[tool.pylint.format]
max-line-length = "80"

[tool.isort]
profile = 'black'
line_length = 80
extend_skip = [".git", "venv"]
