export const GET_SMALL_BUSINESS_DATA_DETAIL = 'AO.GET_SMALL_BUSINESS_DATA_DETAIL'
export const GET_SMALL_BUSINESS_DATA_LAYOUT = 'AO.GET_SMALL_BUSINESS_DATA_LAYOUT'
export const GET_SMALL_BUSINESS_SUPPORT_DATA = 'AO.GET_SMALL_BUSINESS_SUPPORT_DATA'
