CREATE TABLE SAData(
    id INT PRIMARY KEY NOT NULL,
    SA2_code BIGINT NOT NULL ,
    "X.1" VARCHAR(100) ,
    X VARCHAR(100) ,
    state_name VARCHAR(100) ,
    state_code VARCHAR(100) ,
    sa2_name16 VARCHAR(100) ,
    persons_num INT,
    median_persons_age FLOAT,
    males_num INT,
    median_male_age FLOAT,
    females_num INT ,
    median_female_age FLOAT ,
    percentage_person_aged_0_14 FLOAT ,
    percentage_person_aged_15_64 FLOAT ,
    percentage_person_aged_65_plus FLOAT ,
    earners_persons INT,
    median_age_of_earners_years INT,
    gini_coefficient_no FLOAT ,
    median_aud INT,
    mean_aud INT ,
    income_aud BIGINT ,
    highest_quartile_pc FLOAT ,
    income_share_top_5pc FLOAT ,
    third_quartile_pc FLOAT ,
    lowest_quartile_pc FLOAT ,
    income_share_top_1pc FLOAT ,
    second_quartile_pc FLOAT ,
    income_share_top_10pc FLOAT ,
    popfraction DOUBLE PRECISION,
    quartile INT ,
    occup_diversity DOUBLE PRECISION  ,
    bsns_entries INT,
    bsns_exits INT,
    bsns_growth_rate DOUBLE PRECISION ,
    bridge_diversity DOUBLE PRECISION ,
    bridge_rank1 BIGINT ,
    bridge_rank2 BIGINT ,
    bridge_rank3 BIGINT ,
    bridge_rank4 BIGINT ,
    bridge_rank5 BIGINT,
    time_q1 DOUBLE PRECISION ,
    time_q2 DOUBLE PRECISION ,
    time_q3 DOUBLE PRECISION ,
    time_q4 DOUBLE PRECISION ,
    tot_time DOUBLE PRECISION ,
    fq1 DOUBLE PRECISION ,
    fq2 DOUBLE PRECISION ,
    fq3 DOUBLE PRECISION ,
    fq4 DOUBLE PRECISION ,
    income_diversity DOUBLE PRECISION ,
    raw_inequality DOUBLE PRECISION ,
    inequality DOUBLE PRECISION ,
    inflow_r1 BIGINT ,
    inflow_r2 BIGINT ,
    inflow_r3 BIGINT ,
    outflow_r1 BIGINT,
    outflow_r2 BIGINT,
    outflow_r3 BIGINT,
    spent_r1 BIGINT ,
    spent_r2 BIGINT ,
    spent_r3 BIGINT ,
    gain_r1 BIGINT ,
    gain_r2 BIGINT ,
    gain_r3 BIGINT ,
    exchanged_r1 BIGINT ,
    exchanged_r2 BIGINT ,
    exchanged_r3 BIGINT
);

CREATE TABLE sa2data(
    SA2_MAIN16 BIGINT,
    SA2_5DIG16 VARCHAR(100),
    SA2_NAME16 VARCHAR(100),
    SA3_CODE16 VARCHAR(100),
    SA3_NAME16 VARCHAR(100),
    SA4_CODE16 VARCHAR(100),
    SA4_NAME16 VARCHAR(100),
    GCC_CODE16 VARCHAR(100),
    GCC_NAME16 VARCHAR(100),
    STE_CODE16 VARCHAR(100),
    STE_NAME16 VARCHAR(100),
    AREASQKM16 FLOAT,
    "geometry" TEXT
);