from app import db

class SADatabase(db.Model):
    __tablename__ = 'SAdata'

    id = db.Column(db.Integer(), primary_key=True)
    SA2_code = db.Column(db.String(),nullable=False) 
    X.1 = db.Column(db.String())
    X = db.Column(db.String())
    state_name = db.Column(db.String())
    state_code = db.Column(db.String())
    sa2_name16 = db.Column(db.String())   
    persons_num = db.Column(db.String())
    median_persons_age = db.Column(db.String())
    males_num = db.Column(db.String())
    median_male_age = db.Column(db.String())
    females_num = db.Column(db.String())
    median_female_age = db.Column(db.String())
    percentage_person_aged_0_14 = db.Column(db.String())
    percentage_person_aged_15_64 = db.Column(db.String())
    percentage_person_aged_65_plus = db.Column(db.String())
    earners_persons = db.Column(db.String())
    median_age_of_earners_years = db.Column(db.String())
    gini_coefficient_no = db.Column(db.String())
    median_aud = db.Column(db.String())
    mean_aud = db.Column(db.String())
    income_aud = db.Column(db.String())
    highest_quartile_pc = db.Column(db.String())
    income_share_top_5pc = db.Column(db.String())
    third_quartile_pc = db.Column(db.String())
    lowest_quartile_pc = db.Column(db.String())
    income_share_top_1pc = db.Column(db.String())
    second_quartile_pc = db.Column(db.String())
    income_share_top_10pc = db.Column(db.String())
    popfraction = db.Column(db.String())
    quartile = db.Column(db.String())
    occup_diversity = db.Column(db.String())
    bsns_entries = db.Column(db.String())
    bsns_exits = db.Column(db.String())
    bsns_growth_rate = db.Column(db.String())
    bridge_diversity = db.Column(db.String())
    bridge_rank1 = db.Column(db.String())
    bridge_rank2 = db.Column(db.String())
    bridge_rank3 = db.Column(db.String())
    bridge_rank4 = db.Column(db.String())
    bridge_rank5 = db.Column(db.String())
    time_q1 = db.Column(db.String())
    time_q2 = db.Column(db.String())
    time_q3 = db.Column(db.String())
    time_q4 = db.Column(db.String())
    tot_time = db.Column(db.String())
    fq1 = db.Column(db.String())
    fq2 = db.Column(db.String())
    fq3 = db.Column(db.String())
    fq4 = db.Column(db.String())
    income_diversity = db.Column(db.String())
    raw_inequality = db.Column(db.String())
    inequality = db.Column(db.String())
    inflow_r1 = db.Column(db.String())
    inflow_r2 = db.Column(db.String())
    inflow_r3 = db.Column(db.String())
    outflow_r1 = db.Column(db.String())
    outflow_r2 = db.Column(db.String())
    outflow_r3 = db.Column(db.String())
    spent_r1 = db.Column(db.String())
    spent_r2 = db.Column(db.String())
    spent_r3 = db.Column(db.String())
    gain_r1 = db.Column(db.String())
    gain_r2 = db.Column(db.String())
    gain_r3 = db.Column(db.String())
    exchanged_r1 = db.Column(db.String())
    exchanged_r2 = db.Column(db.String())
    exchanged_r3 = db.Column(db.String())

    def __repr__(self):
        return f"<SA2_code {self.SA2_code}>"

